spring:
  datasource:
    host: localhost
    port: 8080
    database: dev_db
    username: dev_user
    password: dev_password
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true