spring:
  profiles:
    active: dev
  datasource:
    host: localhost
    port: 5432
    database: dev_external
    username: dev_external_user
    password: dev_external_password
    url: jdbc:h2:mem:devexternal
    driver-class-name: org.h2.Driver